repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '.*\.ipynb'
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]

ci:
  autoupdate_schedule: monthly
